// defs.append('svg:pattern')
//   .attr('id', 'a-chen')
//   .attr('width', config.avatar_size)
//   .attr('height', config.avatar_size)
//   .attr('patternUnits', 'userSpaceOnUse')
//   .append('svg:image')
//   .attr('xlink:href', achen)
//   .attr('width', config.avatar_size)
//   .attr('height', config.avatar_size)
//   .attr('x', 0)
//   .attr('y', 0);

// defs.append('svg:pattern')
//   .attr('id', 'a-myrzabekova')
//   .attr('width', config.avatar_size)
//   .attr('height', config.avatar_size)
//   .attr('patternUnits', 'userSpaceOnUse')
//   .append('svg:image')
//   .attr('xlink:href', amyrzabekova)
//   .attr('width', config.avatar_size)
//   .attr('height', config.avatar_size)
//   .attr('x', 0)
//   .attr('y', 0);

// defs.append('svg:pattern')
//   .attr('id', 'a-walther')
//   .attr('width', config.avatar_size)
//   .attr('height', config.avatar_size)
//   .attr('patternUnits', 'userSpaceOnUse')
//   .append('svg:image')
//   .attr('xlink:href', awalther)
//   .attr('width', config.avatar_size)
//   .attr('height', config.avatar_size)
//   .attr('x', 0)
//   .attr('y', 0);

// defs.append('svg:pattern')
//   .attr('id', 'b-choy')
//   .attr('width', config.avatar_size)
//   .attr('height', config.avatar_size)
//   .attr('patternUnits', 'userSpaceOnUse')
//   .append('svg:image')
//   .attr('xlink:href', bchoy)
//   .attr('width', config.avatar_size)
//   .attr('height', config.avatar_size)
//   .attr('x', 0)
//   .attr('y', 0);

// defs.append('svg:pattern')
//   .attr('id', 'd-zhong')
//   .attr('width', config.avatar_size)
//   .attr('height', config.avatar_size)
//   .attr('patternUnits', 'userSpaceOnUse')
//   .append('svg:image')
//   .attr('xlink:href', dzhong)
//   .attr('width', config.avatar_size)
//   .attr('height', config.avatar_size)
//   .attr('x', 0)
//   .attr('y', 0);

// defs.append('svg:pattern')
//   .attr('id', 'e-lopes')
//   .attr('width', config.avatar_size)
//   .attr('height', config.avatar_size)
//   .attr('patternUnits', 'userSpaceOnUse')
//   .append('svg:image')
//   .attr('xlink:href', elopes)
//   .attr('width', config.avatar_size)
//   .attr('height', config.avatar_size)
//   .attr('x', 0)
//   .attr('y', 0);

// defs.append('svg:pattern')
//   .attr('id', 'e-xie')
//   .attr('width', config.avatar_size)
//   .attr('height', config.avatar_size)
//   .attr('patternUnits', 'userSpaceOnUse')
//   .append('svg:image')
//   .attr('xlink:href', exie)
//   .attr('width', config.avatar_size)
//   .attr('height', config.avatar_size)
//   .attr('x', 0)
//   .attr('y', 0);

// defs.append('svg:pattern')
//   .attr('id', 'e-tshimanga')
//   .attr('width', config.avatar_size)
//   .attr('height', config.avatar_size)
//   .attr('patternUnits', 'userSpaceOnUse')
//   .append('svg:image')
//   .attr('xlink:href', etshimanga)
//   .attr('width', config.avatar_size)
//   .attr('height', config.avatar_size)
//   .attr('x', 0)
//   .attr('y', 0);

// defs.append('svg:pattern')
//   .attr('id', 'e-bhargava')
//   .attr('width', config.avatar_size)
//   .attr('height', config.avatar_size)
//   .attr('patternUnits', 'userSpaceOnUse')
//   .append('svg:image')
//   .attr('xlink:href', ebhargava)
//   .attr('width', config.avatar_size)
//   .attr('height', config.avatar_size)
//   .attr('x', 0)
//   .attr('y', 0);

// defs.append('svg:pattern')
//   .attr('id', 'e-seo')
//   .attr('width', config.avatar_size)
//   .attr('height', config.avatar_size)
//   .attr('patternUnits', 'userSpaceOnUse')
//   .append('svg:image')
//   .attr('xlink:href', eseo)
//   .attr('width', config.avatar_size)
//   .attr('height', config.avatar_size)
//   .attr('x', 0)
//   .attr('y', 0);

// defs.append('svg:pattern')
//   .attr('id', 'e-chang')
//   .attr('width', config.avatar_size)
//   .attr('height', config.avatar_size)
//   .attr('patternUnits', 'userSpaceOnUse')
//   .append('svg:image')
//   .attr('xlink:href', echang)
//   .attr('width', config.avatar_size)
//   .attr('height', config.avatar_size)
//   .attr('x', 0)
//   .attr('y', 0);

// defs.append('svg:pattern')
//   .attr('id', 'j-wang')
//   .attr('width', config.avatar_size)
//   .attr('height', config.avatar_size)
//   .attr('patternUnits', 'userSpaceOnUse')
//   .append('svg:image')
//   .attr('xlink:href', jwang)
//   .attr('width', config.avatar_size)
//   .attr('height', config.avatar_size)
//   .attr('x', 0)
//   .attr('y', 0);

// defs.append('svg:pattern')
//   .attr('id', 'k-kapoor')
//   .attr('width', config.avatar_size)
//   .attr('height', config.avatar_size)
//   .attr('patternUnits', 'userSpaceOnUse')
//   .append('svg:image')
//   .attr('xlink:href', kkapoor)
//   .attr('width', config.avatar_size)
//   .attr('height', config.avatar_size)
//   .attr('x', 0)
//   .attr('y', 0);

// defs.append('svg:pattern')
//   .attr('id', 's-li')
//   .attr('width', config.avatar_size)
//   .attr('height', config.avatar_size)
//   .attr('patternUnits', 'userSpaceOnUse')
//   .append('svg:image')
//   .attr('xlink:href', sli)
//   .attr('width', config.avatar_size)
//   .attr('height', config.avatar_size)
//   .attr('x', 0)
//   .attr('y', 0);

// defs.append('svg:pattern')
//   .attr('id', 'v-wong')
//   .attr('width', config.avatar_size)
//   .attr('height', config.avatar_size)
//   .attr('patternUnits', 'userSpaceOnUse')
//   .append('svg:image')
//   .attr('xlink:href', vwong)
//   .attr('width', config.avatar_size)
//   .attr('height', config.avatar_size)
//   .attr('x', 0)
//   .attr('y', 0);

// defs.append('svg:pattern')
//   .attr('id', 'v-chen')
//   .attr('width', config.avatar_size)
//   .attr('height', config.avatar_size)
//   .attr('patternUnits', 'userSpaceOnUse')
//   .append('svg:image')
//   .attr('xlink:href', vchen)
//   .attr('width', config.avatar_size)
//   .attr('height', config.avatar_size)
//   .attr('x', 0)
//   .attr('y', 0);

// defs.append('svg:pattern')
//   .attr('id', 'w-cruzlopez')
//   .attr('width', config.avatar_size)
//   .attr('height', config.avatar_size)
//   .attr('patternUnits', 'userSpaceOnUse')
//   .append('svg:image')
//   .attr('xlink:href', wcruzlopez)
//   .attr('width', config.avatar_size)
//   .attr('height', config.avatar_size)
//   .attr('x', 0)
//   .attr('y', 0);
